repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        args: [--explicit-package-bases, --namespace-packages]
