name: MyPy

on:
  workflow_dispatch:

  push:
    branches: [ main, staging ]
    paths:
      - 'src/relic/**'
      - '.github/workflows/mypy.yml'
      - 'mypy.ini'
  pull_request:
    branches: [ main, staging ]
    paths:
      - 'src/relic/**'
      - '.github/workflows/mypy.yml'
      - 'mypy.ini'

jobs:
  mypy:
    uses: MAK-Relic-Tool/Workflows/.github/workflows/mypy.yml@main
    with:
      package: "relic.core"
      mypy-config: "pyproject.toml"
