name: Pytest

on:
  workflow_dispatch:

  push:
    branches: [main, staging]
    paths:
    - src/**
    - tests/**
    - .github/workflows/pytest.yml
    - pyproject.toml
    - MANIFEST.in
    - test-requirements.txt

  pull_request:
    branches: [main, staging]
    paths:
    - src/**
    - tests/**
    - .github/workflows/pytest.yml
    - pyproject.toml
    - MANIFEST.in
    - test-requirements.txt

jobs:
  pytest:
    uses: MAK-Relic-Tool/Workflows/.github/workflows/pytest.yml@main
